server:
  servlet:
    context-path: /api
  port: 8080


jwt:
  token:
    private-key: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAJP+0MFW9NFWzIPKD5Vp7qVNqKdaOY1stYLhskUzI5zKrPp7vXZy0icJMqlVEmpTpZ+lZWerv3gUr9Mq1DRqL2hu0iToTKUnRT4/iwOgPCe+0ev/q8wfCYeHQ5ZUisonofJ/dU0s6XGHfC5CUwfE9L3ILvGy8dME3S9bZScJJNZhAgMBAAECgYB3ViwjGulCvIkhZBf41Xi4Fsz+VYS/A3/B0BieMERxNAUT3h/CmYfYLlSJsq2sy1JsT0RbumQkghndX1XKBi2+9Yq8mu99HJYIsNWLkOCwSYyaTHyp3rr9gyyQ0EcTAm0d5OHnq8vjhSu8YrRDPB0WMcGmJ03i/LahRCItR0QdoQJBAPz+Ny7qBdr4tXgud2yK9u9dC2C4xpqKS6bJhDEVbfOUVz/jUvXCZHmt9W/kDjlI931Fh5HUVirghTWaUGrd1A0CQQCVwR9Zs2yi6Kse0ZfEmiy9c3G6+7XfAMmocpxZ2bKx++nj3oiSCHe1thv/GqpefehX/fbhMyPg++PAfeUYe1KlAkEAgZkoY5v2S+nD7EDBZJT7UjrzrSR6eIgHoPTyBsLXhEOlPlERGlvuZHa8mAjXUHkUbtPDUuzXBzfkhUT7lQL1sQJAZqMPDpaXrWvT5HJ4F0onwcy+tQ3RT78ldyreGALJo4zpd8DMT3I4QbVHqOcov0yCEtTAAQbg31EkfoiKnOXg9QJAI8g4kZM8fRmU8NkkiAyrDIZE40d4JPYy0vHZy3ML7ORL3Ni36WyRzbFMLaXnzZhesVmQReILaomWITTlKGBsFQ==
    public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCT/tDBVvTRVsyDyg+Vae6lTainWjmNbLWC4bJFMyOcyqz6e712ctInCTKpVRJqU6WfpWVnq794FK/TKtQ0ai9obtIk6EylJ0U+P4sDoDwnvtHr/6vMHwmHh0OWVIrKJ6Hyf3VNLOlxh3wuQlMHxPS9yC7xsvHTBN0vW2UnCSTWYQIDAQAB
    access-token-validity-time: 3600000
    refresh-token-validity-time: 108000000